### ISSUE TITLE
New temporary VAT rates due to COVID in 2020

### ISSUE THREAD

**Issue by GregOriol** [kdeldycke/vat-rates#13]
Hello,

It seems that there have been quite a LOT of new and temporary VAT rates changes applied in many countries, including some EU ones.
More info found here: https://www.avalara.com/vatlive/en/vat-news/covid-19-vat-rate-changes.html

Most are exceptions for some category, but one major change seems to be (so far):

* Germany's Standard rate : 19% -> 16% from 01 Jul 2020 to 31 Dec 2020
* Germany's Reduced rate : 7% -> 5% from 01 Jul 2020 to 31 Dec 2020

**Comment by timwhitlock** [comment]
I've just added the reduction in Germany's standard rate to [my fork](https://github.com/timwhitlock/vat-rates/commit/e1ca0caa21d376d68820c4f229091cb73c508060). If it looks correct, I'll make a pull request.

I only maintain this for my own purposes, so I only modify standard rates that apply to SaaS subscription businesses.

Looks like Germany is the only EU standard rate drop. Am I right?

**Comment by GregOriol** [comment]
@timwhitlock Your change seems correct to me

**Comment by kdeldycke** [comment]
Thanks! This has been merged in #14 ! :)
