### ISSUE TITLE
Link to "European Commission country codes" doesn't work

### ISSUE THREAD

**Issue by GregOriol** [kdeldycke/vat-rates#6]
The link to "European Commission country codes" in the README (https://publications.europa.eu/code/pdf/370000en.htm#pays) shows a Page not found.

Not sure, but there seem to be a bad redirection when calling it with https?

**Comment by kdeldycke** [comment]
Fixed! Turns out sone legacy `europa.eu` servers are doesn't support HTTPS! 😄
