### ISSUE TITLE
Croatia VAT rate not reduced in 2018

### ISSUE THREAD

**Issue by timwhitlock** [kdeldycke/vat-rates#8]
Hi.

Further to [my comment on your commit](https://github.com/kdeldycke/vat-rates/commit/b12dc6d2a0e4eae4e3a47722aa1ae64c39637eb5), it seems [Croatia u-turned on their VAT reduction](https://seenews.com/news/croatia-will-not-change-vat-rate-in-2018-fin-min-598721), so it should remain at 25%

**Comment by kdeldycke** [comment]
It seems you're right ! 😭

I'll try to find other sources to confirm the reversal.

**Comment by timwhitlock** [comment]
I can't find a better announcement about the reversal, but the EU's [Taxes in Europe Database](http://ec.europa.eu/taxation_customs/tedb/splSearchForm.html) shows 25% as the current rate.

Permalink (hopefully):
http://ec.europa.eu/taxation_customs/tedb/taxDetails.html?id=3202/1514764800#rate_structureTitle1

**Comment by GregOriol** [comment]
Seems like this official doc, updated on jan 1st, says 25% too: https://ec.europa.eu/taxation_customs/sites/taxation/files/resources/documents/taxation/vat/how_vat_works/rates/vat_rates_en.pdf

**Comment by jeff1985** [comment]
Google search returns a lot of websites showing 25% as current rate. It seems that the change in VAT will be made in 2019, not 2018!

**Comment by GregOriol** [comment]
@jeff1985 Could you provide some sources?

As far as I can see, the change was a proposal, and not validated. The latest news I found is that it's not changing to 24% until 2020:
https://www.tax-news.com/news/Croatia_To_Delay_VAT_Rate_Cut_Until_2020____86885.html
https://www.vatlive.com/vat-news/croatia-delays-1-vat-cut-till-2020/

**Comment by jeff1985** [comment]
@GregOriol 
here are some german and english sources
https://www.accordancevat.com/vat-guide/eu-country-vat-profiles/croatia-hr/
http://www.die-mehrwertsteuer.de/de/umsatzsteuer-kroatien.html
https://www.hk24.de/produktmarken/beratung-service/recht_und_steuern/steuerrecht/umsatzsteuer_mehrwertsteuer/umsatzsteuer_mehrwertsteuer_international/warenhandel/umsatzsteuersaetze-eu-drittstaaten/1167702

this site is stating that the change from 25% to 24% will be effective on 01.01.2019 
https://www.vatlive.com/vat-news/croatia-cuts-vat-to-24-2019/

**Comment by alesvaupotic** [comment]
Guys, as I crawl the official pages of Croatian Ministry of Finance, Tax Administration department, I see no change as of 2018, but some national news agencies are reporting possible changes in 2019.

**Comment by GregOriol** [comment]
@jeff1985 The vatlive news you point to dates from "Tue 19th Jun 2018" while the one I was pointing to dates from "Wed 15th Aug 2018"; so mine is likely the newest news on this.

@alesvaupotic As I understand it, this VAT change in Croatia was a promise made by the government to lower from 25% to 24%, and it was promised to be on 1st Jan 2019; but it was later annouced as delayed to be on 1st Jan 2020.

**Comment by jeff1985** [comment]
@kdeldycke Here is one more official source stating 25% VAT for HR:
https://europa.eu/youreurope/business/taxation/vat/vat-rules-rates/index_en.htm
(open "VAT rates applied in EU member countries")

**Comment by kdeldycke** [comment]
Closed by #9.
